<a href="https://colab.research.google.com/github/SaraPitouli/SaraPitouli.github.io/blob/main/Task7_graph2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df= pd.read_csv('Task7_dataNEW.csv')
df

    Decile   Value                Category
0         1   12.5   CPI by income decile
1         2   11.9   CPI by income decile
2         3   12.5   CPI by income decile
3         4   11.6   CPI by income decile
4         5   11.7   CPI by income decile
5         6   11.0   CPI by income decile
6         7   11.2   CPI by income decile
7         8   10.7   CPI by income decile
8         9   10.5   CPI by income decile
9        10    9.6   CPI by income decile
10        1   10.6  CPIH by income decile
11        2   10.5  CPIH by income decile
12        3   10.7  CPIH by income decile
13        4   10.1  CPIH by income decile
14        5   10.1  CPIH by income decile
15        6    9.6  CPIH by income decile
16        7    9.6  CPIH by income decile
17        8    9.3  CPIH by income decile
18        9    9.1  CPIH by income decile
19       10    8.5  CPIH by income decile

In [ ]:
exported_values= list(df.T.to_dict().values())
exported_values
import json
open('Task7_graph2.json','w').write(json.dumps(exported_values))

1366